---
title: 'Install R and RStudio'
---

To work with R, you will need to install two pieces of software.

* **R**. This is the actual R software, that is used to run R code. 
* **RStudio**. This is a graphical user interface (GUI) that makes working with R much easier. While it is not required to use R, and there are other GUI's available, using RStudio is highly recommended.  

Both programs can be downloaded for free, and are available for all main operating systems (Windows, macOS and Linux).

## Installing R

To install R, you can download it from the [CRAN (comprehensive R Archive Network) website](https://cran.r-project.org/). Do not be alarmed by the website's 90's aesthetics. R itself is cold, dry, no-nonsense software. The decorations come with RStudio.   

## Installing RStudio

RStudio can be downloaded from the [posit.co website](https://posit.co/download/rstudio-desktop), which is the developer of RStudio. Make sure to pick the latest version available for your operating system.

[Continue](1_using-rstudio.qmd){.continue role="button"}
